// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/**
 * Primary content in YouTube → Primary
 *
 */
interface YouTubeSliceDefaultPrimary {
    /**
     * youtubeId field in *YouTube → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: CX25cnGb-IU
     * - **API ID Path**: you_tube.primary.youtubeid
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    youtubeid: prismicT.KeyTextField;
    /**
     * title field in *YouTube → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: you_tube.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * thumbnailOverride field in *YouTube → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: you_tube.primary.thumbnailoverride
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnailoverride: prismicT.ImageField<never>;
    /**
     * caption field in *YouTube → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: you_tube.primary.caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption: prismicT.RichTextField;
}
/**
 * Default variation for YouTube Slice
 *
 * - **API ID**: `default`
 * - **Description**: `YouTube`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type YouTubeSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<YouTubeSliceDefaultPrimary>, never>;
/**
 * Slice variation for *YouTube*
 *
 */
type YouTubeSliceVariation = YouTubeSliceDefault;
/**
 * YouTube Shared Slice
 *
 * - **API ID**: `you_tube`
 * - **Description**: `YouTube`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type YouTubeSlice = prismicT.SharedSlice<"you_tube", YouTubeSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client;
    }
    namespace Content {
        export type { YouTubeSliceDefaultPrimary, YouTubeSliceDefault, YouTubeSliceVariation, YouTubeSlice };
    }
}
